export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
  textOperators: [
    { label: "Contains", value: "ilike" as const },
    { label: "Does not contain", value: "not.ilike" as const },
    { label: "Is", value: "eq" as const },
    { label: "Is not", value: "not.eq" as const },
    { label: "Is empty", value: "empty" as const },
    { label: "Is not empty", value: "not.empty" as const },
  ],
  numericOperators: [
    { label: "Is", value: "eq" as const },
    { label: "Is not", value: "not.eq" as const },
    { label: "Is less than", value: "lt" as const },
    { label: "Is less than or equal to", value: "lte" as const },
    { label: "Is greater than", value: "gt" as const },
    { label: "Is greater than or equal to", value: "gte" as const },
    { label: "Is between", value: "between" as const },
    { label: "Is empty", value: "empty" as const },
    { label: "Is not empty", value: "not.empty" as const },
  ],
  dateOperators: [
    { label: "Is", value: "eq" as const },
    { label: "Is not", value: "not.eq" as const },
    { label: "Is before", value: "lt" as const },
    { label: "Is after", value: "gt" as const },
    { label: "Is on or before", value: "lte" as const },
    { label: "Is on or after", value: "gte" as const },
    { label: "Is between", value: "between" as const },
    { label: "Is empty", value: "empty" as const },
    { label: "Is not empty", value: "not.empty" as const },
  ],
  selectOperators: [
    { label: "Is", value: "eq" as const },
    { label: "Is not", value: "not.eq" as const },
    { label: "Is empty", value: "empty" as const },
    { label: "Is not empty", value: "not.empty" as const },
  ],
  multiSelectOperators: [
    { label: "Has any of", value: "in" as const },
    { label: "Has none of", value: "not.in" as const },
    { label: "Is empty", value: "empty" as const },
    { label: "Is not empty", value: "not.empty" as const },
  ],
  booleanOperators: [
    { label: "Is", value: "eq" as const },
    { label: "Is not", value: "not.eq" as const },
  ],
  sortOrders: [
    { label: "Asc", value: "asc" as const },
    { label: "Desc", value: "desc" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "ilike",
    "not.ilike",
    "eq",
    "not.eq",
    "in",
    "not.in",
    "empty",
    "not.empty",
    "lt",
    "lte",
    "gt",
    "gte",
    "between",
    "isRelativeToToday",
  ] as const,
  joinOperators: ["and", "or"] as const,
};
